# Generated by Django 6.1.1 on 2026-09-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('joindate', models.DateField(auto_now=True)),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
    ]
